org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Project
version=1.0.0
group=com.example.epsilonaddon
java_version=25
# Common
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
mod_id=epsilon_addon_template
mod_name=Epsilon Addon Template
mod_author=Your Name
license=Apache-2.0
credits=
description=A minimal multiloader addon template for OpenEpsilon.
epsilon_version=2026.5.3
epsilon_common_jar=epsilon-common-26.1.2-2026.5.3.jar
epsilon_fabric_jar=epsilon-fabric-26.1.2-2026.5.3.jar
epsilon_neoforge_jar=epsilon-neoforge-26.1.2-2026.5.3.jar
neo_form_version=26.1.2-1

# Fabric
fabric_version=0.146.1+26.1.2
fabric_loader_version=0.19.2

# NeoForge
neoforge_version=26.1.2.4-beta
neoforge_loader_version_range=[4,)
